pool: default #Or use 'Private Linux' if needed.
stages:
- stage:
  jobs:
  - deployment: Deploymentjob
    environment: 'ServiceNow test'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Add all steps needed to deploy your app.
        on:
          success:
            pool: server
            steps:
            - task: UpdateServiceNowChangeRequest@2
              condition: succeeded()
              displayName: 'Update ServiceNow Chnage Request'
              inputs:
                ServiceNowConnection: 'ALM ServiceNow'
                NewStatus: '-1'
                WorkNotes: 'Automated deployment successful'
                otherParameters: '{"u_successful_completion":"Yes"}'
          failure:
            pool: server
            steps:
            - task: UpdateServiceNowChangeRequest@2
              displayName: 'Update ServiceNow Chanage Request'
              inputs:
                ServiceNowConnection: 'ALM ServiceNow'
                NewStatus: '-1'
                WorkNotes: 'Automated deployment unsuccessful'
                otherParameters: '{"u_successful_completion":"No"}'